apiVersion: v1
kind: Service
metadata:
  name: focalboard-svc
  labels:
    {{- include "focalboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "focalboard.selectorLabels" . | nindent 4 }}