apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard-pvc
  namespace: focalboard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
